name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publishtofirebase
      - fastlane

  pull_request:
    branches:
      - main
      - publishtofirebase
      - fastlane

#w
env:
  GITHUB_TOKEN: ${{ secrets.MY_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Our Test
        run: flutter test
      
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
          working-directory: android

      - name: deploy to firebse via fastlane
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        run:
          bundle exec fastlane deploy_to_firebase 