name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publishtofirebase

  pull_request:
    branches:
      - main
      - publishtofirebase

env:
  GITHUB_TOKEN: ${{ secrets.MY_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.32.1
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.0"
          bundler-cache: true
          working-directory: android


      - name: Deploy to Firebase via Fastlane
        working-directory: android

        env:
          FIREBASE_APP_ID: ${{secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}

        run: |
          bundle exec fastlane deploy_to_firebase
